# Generated by Django 5.1.15 on 2026-08-21 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10, verbose_name='المستوى')),
                ('title', models.CharField(max_length=255, verbose_name='اسم الكتاب')),
                ('description', models.TextField(verbose_name='وصف الكتاب ومحتوياته')),
                ('pages_count', models.IntegerField(default=200, verbose_name='عدد الصفحات')),
                ('price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='السعر بالجنيه')),
                ('has_audio_qr', models.BooleanField(default=True, verbose_name='يحتوي على تسجيلات صوتية QR')),
                ('in_stock', models.BooleanField(default=True, verbose_name='متوفر في المخزن')),
            ],
            options={
                'verbose_name': 'كتاب المنهج',
                'verbose_name_plural': 'متجر كتب دويتشه فيلت',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1 - Anfänger'), ('A2', 'A2 - Grundstufe'), ('B1', 'B1 - Mittelstufe'), ('B2', 'B2 - Gute Mittelstufe'), ('C1', 'C1 - Oberstufe (قريباً)'), ('C2', 'C2 - Exzellente Kenntnisse (قريباً)'), ('Upskilling', 'Upskilling & Call Center'), ('Medizin', 'Medizinisches Deutsch (للأطباء)')], max_length=20, verbose_name='المستوى')),
                ('category', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط ومتقدم'), ('career', 'سوق العمل والشركات'), ('advanced', 'مستويات عليا')], default='beginner', max_length=20, verbose_name='التصنيف')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكورس')),
                ('subtitle', models.CharField(max_length=500, verbose_name='الوصف المختصر')),
                ('hours', models.IntegerField(default=60, verbose_name='عدد الساعات التدريبية')),
                ('lectures', models.IntegerField(default=24, verbose_name='عدد المحاضرات')),
                ('duration', models.CharField(default='شهران ونصف', max_length=100, verbose_name='المدة الزمنية')),
                ('price', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10, verbose_name='السعر بالجنيه')),
                ('status', models.CharField(choices=[('open', 'متاح للتسجيل'), ('coming_soon', 'قريباً'), ('closed', 'مكتمل')], default='open', max_length=20, verbose_name='حالة التسجيل')),
                ('featured', models.BooleanField(default=False, verbose_name='كورس مميز / الأكثر طلباً')),
                ('syllabus', models.TextField(help_text='نقاط المنهج مفصولة بأسطر جديدة', verbose_name='محاور المنهج')),
                ('audio_sample', models.TextField(blank=True, null=True, verbose_name='جملة النطق الصوتي التفاعلي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'كورس ألماني',
                'verbose_name_plural': 'الكورسات والمستويات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlacementQuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('score_percentage', models.IntegerField(verbose_name='نسبة النتيجة %')),
                ('recommended_level', models.CharField(max_length=20, verbose_name='المستوى الموصى به')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نتيجة اختبار تحديد مستوى',
                'verbose_name_plural': 'نتائج اختبارات تحديد المستوى',
            },
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='اسم المشتري')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='عنوان التوصيل بالتفصيل')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('total_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد التجهيز ⏳'), ('shipped', 'تم الشحن 🚚'), ('delivered', 'تم الاستلام والتسليم ✅'), ('cancelled', 'ملغي ❌')], default='pending', max_length=20, verbose_name='حالة الشحن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.book', verbose_name='الكتاب المطلوب')),
            ],
            options={
                'verbose_name': 'طلب كتاب',
                'verbose_name_plural': 'طلبات شحن الكتب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(max_length=50, unique=True, verbose_name='كود التسجيل')),
                ('student_name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف (واتساب)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('payment_method', models.CharField(choices=[('vodafone_cash', 'فودافون كاش'), ('instapay', 'إنستاباي'), ('bank_transfer', 'تحويل بنكي'), ('card', 'فيزا / ماستركارد')], default='vodafone_cash', max_length=50, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الطالب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار ⏳'), ('confirmed', 'مؤكد ✅'), ('paid', 'تم الدفع 💰'), ('cancelled', 'ملغي ❌')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='academy.course', verbose_name='الكورس المختار')),
            ],
            options={
                'verbose_name': 'حجز طالب',
                'verbose_name_plural': 'تسجيلات وحجوزات الطلاب',
                'ordering': ['-registered_at'],
            },
        ),
    ]
