# Generated by Django 5.1.15 on 2026-09-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفرع')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة / المحافظة')),
                ('branch_type', models.CharField(choices=[('physical', 'فرع رئيسي / فرعي'), ('online', 'أونلاين (Live)')], default='physical', max_length=20, verbose_name='نوع الفرع')),
                ('address', models.TextField(verbose_name='العنوان التفصيلي')),
                ('map_url', models.TextField(verbose_name='رابط الخريطة أو الواتساب')),
                ('badge', models.CharField(blank=True, default='', max_length=100, verbose_name='الشارة الترويجية')),
                ('phone', models.CharField(default='010552287454', max_length=20, verbose_name='هاتف الفرع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فرع الأكاديمية',
                'verbose_name_plural': 'فروع دويتشه فيلت',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('student_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='هاتف الطالب')),
                ('level', models.CharField(default='A1', max_length=10, verbose_name='المستوى')),
                ('lesson_title', models.CharField(default='المحاضرة العامة', max_length=255, verbose_name='عنوان المحاضرة')),
                ('text', models.TextField(verbose_name='نص التعليق / السؤال')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة ⏳'), ('approved', 'معتمد ومنشور ✅'), ('rejected', 'مرفوض ❌')], default='pending', max_length=20, verbose_name='حالة الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'تعليق المحاضرة',
                'verbose_name_plural': 'اعتماد تعليقات الدروس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('level', models.CharField(max_length=10, verbose_name='المستوى المطلوب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار ⏳'), ('approved', 'مقبول ومفعل ✅'), ('rejected', 'مرفوض ❌')], default='pending', max_length=20, verbose_name='الحالة')),
                ('amount', models.CharField(default='1200 EGP', max_length=50, verbose_name='المبلغ')),
                ('payment_method', models.CharField(default='فودافون كاش', max_length=50, verbose_name='طريقة الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
            options={
                'verbose_name': 'طلب اشتراك بمستوى',
                'verbose_name_plural': 'طلبات تفعيل المستويات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bookorder',
            name='book_name_cache',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الكتاب'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='course_title_cache',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الكورس النصي'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.book', verbose_name='الكتاب المطلوب'),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='order_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الطلب'),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, default='', help_text='نقاط المنهج مفصولة بأسطر جديدة', verbose_name='محاور المنهج'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='academy.course', verbose_name='الكورس المختار'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='registration_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='كود التسجيل'),
        ),
        migrations.CreateModel(
            name='AcademyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('level', models.CharField(default='A1', max_length=10, verbose_name='المستوى الدراسي')),
                ('status', models.CharField(choices=[('active', 'نشط ومفعل ✅'), ('suspended', 'موقوف مؤقتاً ⏸️')], default='active', max_length=20, verbose_name='الحالة')),
                ('progress', models.IntegerField(default=0, verbose_name='نسبة الإنجاز %')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طالب الأكاديمية',
                'verbose_name_plural': 'دليل الطلاب',
                'ordering': ['-id'],
            },
        ),
    ]
