# Generated by Django 5.1.15 on 2026-09-26 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_branch_lessoncomment_levelenrollmentrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A1', 'A1 - للمبتدئين من الصفر'), ('A2', 'A2 - المحادثة والتأسيس الثاني'), ('B1', 'B1 - مؤهل السفر والكول سنتر'), ('B2', 'B2 - الطلاقة والكفاءة التخصصية')], max_length=10, unique=True, verbose_name='رمز المستوى')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان الكامل')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر القديم (للخصم)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('bunny_collection_id', models.CharField(blank=True, default='', max_length=255, verbose_name='معرف Collection في Bunny Stream')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مستوى دراسي',
                'verbose_name_plural': 'المستويات الدراسية',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DigitalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم الكتاب')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('General', 'عام')], max_length=10, verbose_name='المستوى')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('file', models.FileField(upload_to='digital_books/', verbose_name='ملف PDF')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'كتاب رقمي',
                'verbose_name_plural': 'الكتب الرقمية',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('otp', models.CharField(max_length=6, verbose_name='رمز التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'رمز إعادة تعيين كلمة المرور',
                'verbose_name_plural': 'رموز إعادة تعيين كلمة المرور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم الملف')),
                ('file', models.FileField(upload_to='course_files/', verbose_name='ملف PDF')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='academy.courselevel', verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'ملف المستوى',
                'verbose_name_plural': 'ملفات المستويات',
                'ordering': ['level', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_book_accesses', to=settings.AUTH_USER_MODEL, verbose_name='منحه الوصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_accesses', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='academy.digitalbook', verbose_name='الكتاب')),
            ],
            options={
                'verbose_name': 'صلاحية كتاب',
                'verbose_name_plural': 'صلاحيات الكتب',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='LevelAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المنح')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات (طريقة الدفع، إلخ)')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='منحه الوصول')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='academy.courselevel', verbose_name='المستوى')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_accesses', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'صلاحية مستوى',
                'verbose_name_plural': 'صلاحيات الوصول للمستويات',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'level')},
            },
        ),
        migrations.CreateModel(
            name='SocialAuthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حساب اجتماعي مرتبط',
                'verbose_name_plural': 'الحسابات الاجتماعية المرتبطة',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان المحاضرة')),
                ('bunny_video_id', models.CharField(max_length=255, unique=True, verbose_name='معرف الفيديو في Bunny Stream')),
                ('length', models.PositiveIntegerField(default=0, verbose_name='المدة بالثواني')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='academy.courselevel', verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'محاضرة فيديو',
                'verbose_name_plural': 'محاضرات الفيديو',
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.IntegerField(db_index=True, verbose_name='معرف المستوى')),
                ('video_id', models.CharField(db_index=True, max_length=255, verbose_name='معرف الفيديو (Bunny)')),
                ('content', models.TextField(max_length=2000, verbose_name='محتوى التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='academy.videocomment', verbose_name='تعليق أصلي (للردود)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تعليق فيديو',
                'verbose_name_plural': 'تعليقات الفيديوهات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level_id', 'video_id'], name='academy_vid_level_i_b2bb63_idx')],
            },
        ),
    ]
