# Generated by Django 5.1.15 on 2026-09-26 16:33

import academy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_courselevel_digitalbook_passwordresetotp_coursefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='file',
            field=models.FileField(storage=academy.storage.get_protected_storage, upload_to='course_files/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='digitalbook',
            name='file',
            field=models.FileField(storage=academy.storage.get_protected_storage, upload_to='digital_books/', verbose_name='ملف PDF'),
        ),
    ]
