# Generated by Django 5.1.15 on 2026-09-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_protected_file_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الإعلان (إظهار / إخفاء)')),
                ('tag', models.CharField(default='🔥 عرض خاص', max_length=100, verbose_name='شارة الإعلان (الوسم)')),
                ('title', models.CharField(default='خصم خاص 25% على باقة المستويات المجمعة', max_length=255, verbose_name='عنوان الإعلان الرئيسي')),
                ('desc', models.TextField(default='التسجيل متاح الآن للدفعة الجديدة مع محاضرات تفاعلية وبنك أسئلة ومتابعة شخصية مستمرة.', verbose_name='نص الإعلان')),
                ('has_discount', models.BooleanField(default=True, verbose_name='تفعيل شارة الخصم')),
                ('discount_percent', models.CharField(blank=True, default='25%', max_length=50, verbose_name='نسبة الخصم')),
                ('cta_text', models.CharField(default='احجز مقعدك بالخصم', max_length=100, verbose_name='نص زر التفاعل')),
                ('cta_link', models.CharField(default='/#online-courses', max_length=255, verbose_name='رابط الزر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعلان الموقع الترويجي',
                'verbose_name_plural': 'إعلانات الموقع',
            },
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='name',
            field=models.CharField(choices=[('A1', 'A1 - للمبتدئين من الصفر'), ('A2', 'A2 - المحادثة والتأسيس الثاني'), ('B1', 'B1 - مؤهل السفر والكول سنتر'), ('B2', 'B2 - الطلاقة والكفاءة التخصصية'), ('C1', 'C1 - قمة الطلاقة اللغوية والأكاديمية (قريباً)')], max_length=10, unique=True, verbose_name='رمز المستوى'),
        ),
    ]
