# Generated by Django 5.1.15 on 2026-09-28 21:45

import academy.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_siteannouncement_alter_courselevel_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['order', 'id'], 'verbose_name': 'فرع الأكاديمية', 'verbose_name_plural': 'فروع دويتشه فيلت'},
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ظاهر في الموقع'),
        ),
        migrations.AddField(
            model_name='branch',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='رمز المستوى'),
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('level', 'مستوى / كورس'), ('book', 'كتاب')], max_length=10, verbose_name='النوع')),
                ('level_code', models.CharField(db_index=True, max_length=10, verbose_name='المستوى')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('note', models.TextField(blank=True, default='', verbose_name='ملاحظة الطالب')),
                ('receipt', models.FileField(blank=True, storage=academy.storage.get_protected_storage, upload_to='receipts/', verbose_name='صورة التحويل')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول ومفعّل'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=10, verbose_name='الحالة')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='ملاحظة الإدارة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='academy.digitalbook', verbose_name='الكتاب')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='academy.courselevel', verbose_name='المستوى')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='راجعه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طلب تفعيل',
                'verbose_name_plural': 'طلبات التفعيل (كورسات وكتب)',
                'ordering': ['-created_at'],
            },
        ),
    ]
